name: Perl lint

on:
  workflow_call:
    inputs:
      ref:
        description: "The ref of this reusable workflow."
        type: string
        required: true
      apt-packages:
        description:
          "Apt packages needed to install this dist's develop deps, as a string containing a
          whitespace-separated list of packages."
        type: string

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install extra apt packages
        run: |
          set -e
          set -x

          sudo apt-get update
          # This will turn newlines into spaces.
          packages="$(perl -E 'say join q{ }, grep { length } split /\s+/, $ENV{APT_PACKAGES}')"
          sudo apt-get --yes install $packages
        env:
          APT_PACKAGES: ${{ inputs.apt-packages }}
        if: "inputs.apt-packages != ''"

      - name: Check out Perl project repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check out workflow repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: houseabsolute/workflow-perl-dzil-ci
          ref: ${{ inputs.ref }}
          # We have to use `./` at the beginning of a `uses:` path, so putting it under `.git`
          # ensures that tools like `precious` ignore it.
          path: ./.git/.workflow-perl-dzil-ci

      - name: Set up Perl
        uses: ./.git/.workflow-perl-dzil-ci/.github/actions/set-up-perl
        with:
          perl-version: latest
          cache-prefix: lint
          # perlcritic, perltidy, and podtidy are installed as scripts.
          cache-extra: bin
          cache-key-file: cpanfile

      - name: Install mise
        run: |
          set -e
          set -x

          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # perlcritic, perltidy, podchecker, and podtidy are develop deps, so
      # `--with-all` is what pulls them in.
      - name: Install lint tools
        run: |
          cpm install --verbose --show-build-log-on-failure --global --with-all --cpanfile ./cpanfile

      - name: Run precious
        run: mise exec -- precious lint --all
